Instance: Bundle-PatientAdmissionsList-Post
InstanceOf: Bundle
Description: "All resources needed to test patient admissions.  Using PUT's for readability."
Usage: #example
* type = #transaction

// Practitioners

* entry[0].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-GeneralPractitioner"
* entry[=].resource = Practitioner-GeneralPractitioner
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-GeneralPractitioner"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-GlanClwyd-TriageNurse"
* entry[=].resource = Practitioner-GlanClwyd-TriageNurse
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-GlanClwyd-TriageNurse"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-GlanClwyd-Receptionist"
* entry[=].resource = Practitioner-GlanClwyd-Receptionist
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-GlanClwyd-Receptionist"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-GlanClwyd-JuniorDoctor"
* entry[=].resource = Practitioner-GlanClwyd-JuniorDoctor
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-GlanClwyd-JuniorDoctor"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-WrexhamMaelor-TriageNurse"
* entry[=].resource = Practitioner-WrexhamMaelor-TriageNurse
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-WrexhamMaelor-TriageNurse"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-WrexhamMaelor-Receptionist"
* entry[=].resource = Practitioner-WrexhamMaelor-Receptionist
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-WrexhamMaelor-Receptionist"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-WrexhamMaelor-JuniorDoctor"
* entry[=].resource = Practitioner-WrexhamMaelor-JuniorDoctor
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-WrexhamMaelor-JuniorDoctor"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-YsbytyGwynedd-TriageNurse"
* entry[=].resource = Practitioner-YsbytyGwynedd-TriageNurse
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-YsbytyGwynedd-TriageNurse"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-YsbytyGwynedd-Receptionist"
* entry[=].resource = Practitioner-YsbytyGwynedd-Receptionist
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-YsbytyGwynedd-Receptionist"
* entry[+].fullUrl = "https://www.nhs.wales/Practitioner/Practitioner-YsbytyGwynedd-JuniorDoctor"
* entry[=].resource = Practitioner-YsbytyGwynedd-JuniorDoctor
* entry[=].request.method = #PUT
* entry[=].request.url = "Practitioner/Practitioner-YsbytyGwynedd-JuniorDoctor"

// PractitionerRoles

* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-GeneralPractitioner"
* entry[=].resource = PractitionerRole-GeneralPractitioner
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-GeneralPractitioner"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-GlanClwyd-TriageNurse"
* entry[=].resource = PractitionerRole-GlanClwyd-TriageNurse
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-GlanClwyd-TriageNurse"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-GlanClwyd-Receptionist"
* entry[=].resource = PractitionerRole-GlanClwyd-Receptionist
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-GlanClwyd-Receptionist"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-GlanClwyd-JuniorDoctor"
* entry[=].resource = PractitionerRole-GlanClwyd-JuniorDoctor
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-GlanClwyd-JuniorDoctor"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-WrexhamMaelor-TriageNurse"
* entry[=].resource = PractitionerRole-WrexhamMaelor-TriageNurse
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-WrexhamMaelor-TriageNurse"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-WrexhamMaelor-Receptionist"
* entry[=].resource = PractitionerRole-WrexhamMaelor-Receptionist
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-WrexhamMaelor-Receptionist"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-WrexhamMaelor-JuniorDoctor"
* entry[=].resource = PractitionerRole-WrexhamMaelor-JuniorDoctor
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-WrexhamMaelor-JuniorDoctor"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-YsbytyGwynedd-TriageNurse"
* entry[=].resource = PractitionerRole-YsbytyGwynedd-TriageNurse
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-YsbytyGwynedd-TriageNurse"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-YsbytyGwynedd-Receptionist"
* entry[=].resource = PractitionerRole-YsbytyGwynedd-Receptionist
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-YsbytyGwynedd-Receptionist"
* entry[+].fullUrl = "https://www.nhs.wales/PractitionerRole/PractitionerRole-YsbytyGwynedd-JuniorDoctor"
* entry[=].resource = PractitionerRole-YsbytyGwynedd-JuniorDoctor
* entry[=].request.method = #PUT
* entry[=].request.url = "PractitionerRole/PractitionerRole-YsbytyGwynedd-JuniorDoctor"

// Patients

* entry[+].fullUrl = "https://www.nhs.wales/Patient/Patient-AdamTest"
* entry[=].resource = Patient-AdamTest
* entry[=].request.method = #PUT
* entry[=].request.url = "Patient/Patient-AdamTest"
* entry[+].fullUrl = "https://www.nhs.wales/Patient/Patient-BobTest"
* entry[=].resource = Patient-BobTest
* entry[=].request.method = #PUT
* entry[=].request.url = "Patient/Patient-BobTest"
* entry[+].fullUrl = "https://www.nhs.wales/Patient/Patient-CarolTest"
* entry[=].resource = Patient-CarolTest
* entry[=].request.method = #PUT
* entry[=].request.url = "Patient/Patient-CarolTest"
* entry[+].fullUrl = "https://www.nhs.wales/Patient/Patient-DougTest"
* entry[=].resource = Patient-DougTest
* entry[=].request.method = #PUT
* entry[=].request.url = "Patient/Patient-DougTest"
* entry[+].fullUrl = "https://www.nhs.wales/Patient/Patient-EoinTest"
* entry[=].resource = Patient-EoinTest
* entry[=].request.method = #PUT
* entry[=].request.url = "Patient/Patient-EoinTest"
* entry[+].fullUrl = "https://www.nhs.wales/Patient/Patient-FredTest"
* entry[=].resource = Patient-FredTest
* entry[=].request.method = #PUT
* entry[=].request.url = "Patient/Patient-FredTest"

// Organizations

* entry[+].fullUrl = "https://www.nhs.wales/Organization/Organization-GlanClwydHospital"
* entry[=].resource = Organization-GlanClwydHospital
* entry[=].request.method = #PUT
* entry[=].request.url = "Organization/Organization-GlanClwydHospital"
* entry[+].fullUrl = "https://www.nhs.wales/Organization/Organization-WrexhamMaelorHospital"
* entry[=].resource = Organization-WrexhamMaelorHospital
* entry[=].request.method = #PUT
* entry[=].request.url = "Organization/Organization-WrexhamMaelorHospital"
* entry[+].fullUrl = "https://www.nhs.wales/Organization/Organization-YsbytyGwyneddHospital"
* entry[=].resource = Organization-YsbytyGwyneddHospital
* entry[=].request.method = #PUT
* entry[=].request.url = "Organization/Organization-YsbytyGwyneddHospital"
* entry[+].fullUrl = "https://www.nhs.wales/Organization/Organization-GeneralPractitioner"
* entry[=].resource = Organization-GeneralPractitioner
* entry[=].request.method = #PUT
* entry[=].request.url = "Organization/Organization-GeneralPractitioner"
* entry[+].fullUrl = "https://www.nhs.wales/Organization/Organization-CymruHospital"
* entry[=].resource = Organization-CymruHospital
* entry[=].request.method = #PUT
* entry[=].request.url = "Organization/Organization-CymruHospital"

// HealthcareServices

* entry[+].fullUrl = "https://www.nhs.wales/HealthcareService/HealthcareService-GlanClwyd-Medicine"
* entry[=].resource = HealthcareService-GlanClwyd-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "HealthcareService/HealthcareService-GlanClwyd-Medicine"
* entry[+].fullUrl = "https://www.nhs.wales/HealthcareService/HealthcareService-WrexhamMaelor-Medicine"
* entry[=].resource = HealthcareService-WrexhamMaelor-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "HealthcareService/HealthcareService-WrexhamMaelor-Medicine"
* entry[+].fullUrl = "https://www.nhs.wales/HealthcareService/HealthcareService-YsbytyGwynedd-Medicine"
* entry[=].resource = HealthcareService-YsbytyGwynedd-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "HealthcareService/HealthcareService-YsbytyGwynedd-Medicine"

// Locations

* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-GlanClwyd-EDWaitingRoom"
* entry[=].resource = Location-GlanClwyd-EDWaitingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-GlanClwyd-EDWaitingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-WrexhamMaelor-EDWaitingRoom"
* entry[=].resource = Location-WrexhamMaelor-EDWaitingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-WrexhamMaelor-EDWaitingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-YsbytyGwynedd-EDWaitingRoom"
* entry[=].resource = Location-YsbytyGwynedd-EDWaitingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-YsbytyGwynedd-EDWaitingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-GlanClwyd-Medicine"
* entry[=].resource = Location-GlanClwyd-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-GlanClwyd-Medicine"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-WrexhamMaelor-Medicine"
* entry[=].resource = Location-WrexhamMaelor-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-WrexhamMaelor-Medicine"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-YsbytyGwynedd-Medicine"
* entry[=].resource = Location-YsbytyGwynedd-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-YsbytyGwynedd-Medicine"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-GlanClwydHospital"
* entry[=].resource = Location-GlanClwydHospital
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-GlanClwydHospital"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-WrexhamMaelorHospital"
* entry[=].resource = Location-WrexhamMaelorHospital
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-WrexhamMaelorHospital"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-YsbytyGwyneddHospital"
* entry[=].resource = Location-YsbytyGwyneddHospital
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-YsbytyGwyneddHospital"
* entry[+].fullUrl = "https://www.nhs.wales/Location/Location-GeneralPractitioner"
* entry[=].resource = Location-GeneralPractitioner
* entry[=].request.method = #PUT
* entry[=].request.url = "Location/Location-GeneralPractitioner"

// Encounters

* entry[+].fullUrl = "https://www.nhs.wales/Encounter/Encounter-AdamTest-EdWaiting-Admission-Respiratory"
* entry[=].resource = Encounter-AdamTest-EdWaiting-Admission-Respiratory
* entry[=].request.method = #PUT
* entry[=].request.url = "Encounter/Encounter-AdamTest-EdWaiting-Admission-Respiratory"
* entry[+].fullUrl = "https://www.nhs.wales/Encounter/Encounter-BobTest-EdWaiting-Admission-Respiratory"
* entry[=].resource = Encounter-BobTest-EdWaiting-Admission-Respiratory
* entry[=].request.method = #PUT
* entry[=].request.url = "Encounter/Encounter-BobTest-EdWaiting-Admission-Respiratory"
* entry[+].fullUrl = "https://www.nhs.wales/Encounter/Encounter-CarolTest-EdWaiting-Admission-Respiratory"
* entry[=].resource = Encounter-CarolTest-EdWaiting-Admission-Respiratory
* entry[=].request.method = #PUT
* entry[=].request.url = "Encounter/Encounter-CarolTest-EdWaiting-Admission-Respiratory"
* entry[+].fullUrl = "https://www.nhs.wales/Encounter/Encounter-DougTest-EdWaiting-Admission-Respiratory"
* entry[=].resource = Encounter-DougTest-EdWaiting-Admission-Respiratory
* entry[=].request.method = #PUT
* entry[=].request.url = "Encounter/Encounter-DougTest-EdWaiting-Admission-Respiratory"
* entry[+].fullUrl = "https://www.nhs.wales/Encounter/Encounter-EoinTest-EdWaiting-Admission-Respiratory"
* entry[=].resource = Encounter-EoinTest-EdWaiting-Admission-Respiratory
* entry[=].request.method = #PUT
* entry[=].request.url = "Encounter/Encounter-EoinTest-EdWaiting-Admission-Respiratory"
* entry[+].fullUrl = "https://www.nhs.wales/Encounter/Encounter-FredTest-EdWaiting-Admission-Respiratory"
* entry[=].resource = Encounter-FredTest-EdWaiting-Admission-Respiratory
* entry[=].request.method = #PUT
* entry[=].request.url = "Encounter/Encounter-FredTest-EdWaiting-Admission-Respiratory"


// Observations

// Adam Test Observations

* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-AdamTest-NEWS2"
* entry[=].resource = Observation-AdamTest-NEWS2
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-AdamTest-NEWS2"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-AdamTest-ACVPU"
* entry[=].resource = Observation-AdamTest-ACVPU
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-AdamTest-ACVPU"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-AdamTest-BloodPressure"
* entry[=].resource = Observation-AdamTest-BloodPressure
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-AdamTest-BloodPressure"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-AdamTest-BodyTemperature"
* entry[=].resource = Observation-AdamTest-BodyTemperature
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-AdamTest-BodyTemperature"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-AdamTest-BreathingRoom"
* entry[=].resource = Observation-AdamTest-BreathingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-AdamTest-BreathingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-AdamTest-HeartRate"
* entry[=].resource = Observation-AdamTest-HeartRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-AdamTest-HeartRate"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-AdamTest-OxygenSaturation"
* entry[=].resource = Observation-AdamTest-OxygenSaturation
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-AdamTest-OxygenSaturation"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-AdamTest-RespiratoryRate"
* entry[=].resource = Observation-AdamTest-RespiratoryRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-AdamTest-RespiratoryRate"

// Bob Test Observations

* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-BobTest-NEWS2"
* entry[=].resource = Observation-BobTest-NEWS2
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-BobTest-NEWS2"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-BobTest-ACVPU"
* entry[=].resource = Observation-BobTest-ACVPU
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-BobTest-ACVPU"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-BobTest-BloodPressure"
* entry[=].resource = Observation-BobTest-BloodPressure
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-BobTest-BloodPressure"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-BobTest-BodyTemperature"
* entry[=].resource = Observation-BobTest-BodyTemperature
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-BobTest-BodyTemperature"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-BobTest-BreathingRoom"
* entry[=].resource = Observation-BobTest-BreathingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-BobTest-BreathingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-BobTest-HeartRate"
* entry[=].resource = Observation-BobTest-HeartRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-BobTest-HeartRate"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-BobTest-OxygenSaturation"
* entry[=].resource = Observation-BobTest-OxygenSaturation
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-BobTest-OxygenSaturation"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-BobTest-RespiratoryRate"
* entry[=].resource = Observation-BobTest-RespiratoryRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-BobTest-RespiratoryRate"

// Carol Test Observations

* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-CarolTest-NEWS2"
* entry[=].resource = Observation-CarolTest-NEWS2
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-CarolTest-NEWS2"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-CarolTest-ACVPU"
* entry[=].resource = Observation-CarolTest-ACVPU
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-CarolTest-ACVPU"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-CarolTest-BloodPressure"
* entry[=].resource = Observation-CarolTest-BloodPressure
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-CarolTest-BloodPressure"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-CarolTest-BodyTemperature"
* entry[=].resource = Observation-CarolTest-BodyTemperature
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-CarolTest-BodyTemperature"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-CarolTest-BreathingRoom"
* entry[=].resource = Observation-CarolTest-BreathingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-CarolTest-BreathingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-CarolTest-HeartRate"
* entry[=].resource = Observation-CarolTest-HeartRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-CarolTest-HeartRate"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-CarolTest-OxygenSaturation"
* entry[=].resource = Observation-CarolTest-OxygenSaturation
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-CarolTest-OxygenSaturation"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-CarolTest-RespiratoryRate"
* entry[=].resource = Observation-CarolTest-RespiratoryRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-CarolTest-RespiratoryRate"

// Doug Test Observations

* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-DougTest-NEWS2"
* entry[=].resource = Observation-DougTest-NEWS2
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-DougTest-NEWS2"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-DougTest-ACVPU"
* entry[=].resource = Observation-DougTest-ACVPU
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-DougTest-ACVPU"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-DougTest-BloodPressure"
* entry[=].resource = Observation-DougTest-BloodPressure
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-DougTest-BloodPressure"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-DougTest-BodyTemperature"
* entry[=].resource = Observation-DougTest-BodyTemperature
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-DougTest-BodyTemperature"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-DougTest-BreathingRoom"
* entry[=].resource = Observation-DougTest-BreathingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-DougTest-BreathingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-DougTest-HeartRate"
* entry[=].resource = Observation-DougTest-HeartRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-DougTest-HeartRate"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-DougTest-OxygenSaturation"
* entry[=].resource = Observation-DougTest-OxygenSaturation
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-DougTest-OxygenSaturation"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-DougTest-RespiratoryRate"
* entry[=].resource = Observation-DougTest-RespiratoryRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-DougTest-RespiratoryRate"

// Eoin Test Observations

* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-EoinTest-NEWS2"
* entry[=].resource = Observation-EoinTest-NEWS2
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-EoinTest-NEWS2"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-EoinTest-ACVPU"
* entry[=].resource = Observation-EoinTest-ACVPU
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-EoinTest-ACVPU"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-EoinTest-BloodPressure"
* entry[=].resource = Observation-EoinTest-BloodPressure
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-EoinTest-BloodPressure"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-EoinTest-BodyTemperature"
* entry[=].resource = Observation-EoinTest-BodyTemperature
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-EoinTest-BodyTemperature"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-EoinTest-BreathingRoom"
* entry[=].resource = Observation-EoinTest-BreathingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-EoinTest-BreathingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-EoinTest-HeartRate"
* entry[=].resource = Observation-EoinTest-HeartRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-EoinTest-HeartRate"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-EoinTest-OxygenSaturation"
* entry[=].resource = Observation-EoinTest-OxygenSaturation
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-EoinTest-OxygenSaturation"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-EoinTest-RespiratoryRate"
* entry[=].resource = Observation-EoinTest-RespiratoryRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-EoinTest-RespiratoryRate"

// Fred Test Observations

* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-FredTest-NEWS2"
* entry[=].resource = Observation-FredTest-NEWS2
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-FredTest-NEWS2"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-FredTest-ACVPU"
* entry[=].resource = Observation-FredTest-ACVPU
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-FredTest-ACVPU"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-FredTest-BloodPressure"
* entry[=].resource = Observation-FredTest-BloodPressure
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-FredTest-BloodPressure"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-FredTest-BodyTemperature"
* entry[=].resource = Observation-FredTest-BodyTemperature
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-FredTest-BodyTemperature"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-FredTest-BreathingRoom"
* entry[=].resource = Observation-FredTest-BreathingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-FredTest-BreathingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-FredTest-HeartRate"
* entry[=].resource = Observation-FredTest-HeartRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-FredTest-HeartRate"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-FredTest-OxygenSaturation"
* entry[=].resource = Observation-FredTest-OxygenSaturation
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-FredTest-OxygenSaturation"
* entry[+].fullUrl = "https://www.nhs.wales/Observation/Observation-FredTest-RespiratoryRate"
* entry[=].resource = Observation-FredTest-RespiratoryRate
* entry[=].request.method = #PUT
* entry[=].request.url = "Observation/Observation-FredTest-RespiratoryRate"

// Groups

* entry[+].fullUrl = "https://www.nhs.wales/Group/Group-GlanClwyd-Medicine-WaitingRoom"
* entry[=].resource = Group-GlanClwyd-Medicine-WaitingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Group/Group-GlanClwyd-Medicine-WaitingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Group/Group-WrexhamMaelor-Medicine-WaitingRoom"
* entry[=].resource = Group-WrexhamMaelor-Medicine-WaitingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Group/Group-WrexhamMaelor-Medicine-WaitingRoom"
* entry[+].fullUrl = "https://www.nhs.wales/Group/Group-YsbytyGwynedd-Medicine-WaitingRoom"
* entry[=].resource = Group-YsbytyGwynedd-Medicine-WaitingRoom
* entry[=].request.method = #PUT
* entry[=].request.url = "Group/Group-YsbytyGwynedd-Medicine-WaitingRoom"

// CareTeams

* entry[+].fullUrl = "https://www.nhs.wales/CareTeam/CareTeam-GlanClwyd-Medicine"
* entry[=].resource = CareTeam-GlanClwyd-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "CareTeam/CareTeam-GlanClwyd-Medicine"
* entry[+].fullUrl = "https://www.nhs.wales/CareTeam/CareTeam-WrexhamMaelor-Medicine"
* entry[=].resource = CareTeam-WrexhamMaelor-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "CareTeam/CareTeam-WrexhamMaelor-Medicine"
* entry[+].fullUrl = "https://www.nhs.wales/CareTeam/CareTeam-YsbytyGwynedd-Medicine"
* entry[=].resource = CareTeam-YsbytyGwynedd-Medicine
* entry[=].request.method = #PUT
* entry[=].request.url = "CareTeam/CareTeam-YsbytyGwynedd-Medicine"
